Fix v1 vm support
genesis-community/cf-genesis-kit pull request #163
Opened 2021-02-16 00:40 UTC by dennisjbell

# Improvements

- Better support for vm_types, especially in context of upgrading from v1 environments.

  New feature `v1-vm-types` sets up the manifest to use the same VM types as was used in the v1.x versions of the kit, or as close to possible.  This allows you to use your existing cloud config and tuning.  Where the instance group name changes, it will use the vm type that the instance group was migrated from.

  The exceptions are `tcp-router`, which will use the `router` vm type, and `cc-worker` and `credhub`, which continue to use `minimum` as there was no prevous instance group for these functions.

# Bug Fix

- Supplied missing `params.*_vm_types`, warn instead of error if an unknown instance group is specified, so that custom instance groups can be managed in the same way.

  Note:  For known instance groups, the underscores are automatically converted to hyphens to determine the matching instance_group for the specified `*_vm_type` params.  For user specified, you must specify the hyphen or underscore as used in the instance_group.

  Known instance groups are:
    adapter, api, cc-worker, credhub, database, diego-api, diego-cell, doppler, errand, haproxy, log-api, nats, rotate-cc-database-key, router, scheduler, singleton-blobstore, smoke-tests, tcp-router, and uaa

2021-02-16 07:32 UTC, rkoster requested changes
Looks good, but is hard to judge if it actually works without a spec test.
Maybe add a deployment where migrated_v1_env is set in exodus.

2021-02-18 08:14 UTC, rkoster commented
@dennisjbell please review and merge https://github.com/dennisjbell/cf-genesis-kit/pull/1 into your feature branch.

2021-02-19 19:09 UTC, dennisjbell commented on spec/results/override-vm-types-and-counts-old-names.yml
> +  vm_type: minimal
not with old-names test (there was no credhub instance in the old kit)

2021-02-19 19:10 UTC, rkoster approved these changes

2021-02-19 19:11 UTC, rkoster commented
LGTM!

2021-02-23 00:49 UTC, krutten approved these changes
Reviewed changes and test cases.  LGTM

2021-02-23 00:55 UTC, krutten commented on MANUAL.md
> +If you want to use the de facto vm types after migration, you can specify the
Clarifier:  Should state that `no-v1-vm-types` is a feature so it's clear where it goes.

2021-02-23 01:04 UTC, merged