adds v1 vm fixes back in
genesis-community/cf-genesis-kit pull request #174
Opened 2021-06-17 14:50 UTC by dandersonsw

This adds back in the code needed for CF deployments upgraded from v1.10 to 2.x

2021-06-17 21:58 UTC, dennisjbell requested changes
Please also include the changes for nats users (commits 9698794650c017bc574332aab9be1462d80f8a9e and 34afc91f6d0d77cb531349aa0a72a2f4a2f4ecfa), as well as the blobstore name fix (commit 1a68c0a75ebe720c29732241ad77dc03bbcbcf41).  These impact the v1 migration story.

2021-06-17 21:58 UTC, dennisjbell commented on hooks/blueprint
> +        "overlay/db/internal-overrides.yml" \
Indentation changes for no reason

2021-06-17 21:58 UTC, dennisjbell commented on hooks/blueprint
> +
Unnecessary blank line

2021-06-18 14:34 UTC, dandersonsw commented
I've added the requested commits, and fixed the indentation and removed the unnecessary blank line.

2021-06-21 22:02 UTC, dennisjbell approved these changes

2021-06-21 22:03 UTC, merged