NFS Network/AZ Fix
genesis-community/cf-genesis-kit pull request #184
Opened 2022-03-04 20:36 UTC by antitux

Fixing bug that would likely cause the `nfs-broker-push` instance to not come up in the correct AZ/Network

2022-03-04 20:57 UTC, xiujiao requested changes
Hi For network change from default to other name, you can see how it is done here
https://github.com/genesis-community/cf-genesis-kit/blob/main/operations/rename-network-and-deployment.yml
you do not need to specify az

The RR need submit against develop instead of main

2022-03-04 21:36 UTC, antitux commented
Because it's a non-core feature, it does unfortunately need a separate ops file.

2022-03-07 13:05 UTC, xiujiao approved these changes

2022-03-07 16:04 UTC, antitux commented
Closing this PR and rebasing against develop.

2022-03-07 16:04 UTC, closed without merging